### ISSUE TITLE
Will you support proper semantic versioning from now on ?

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#5]
Because it's seems that you have done some crazy stuff lately. 

http://semver.org

**Comment by d-theo** [comment]
We are currently using the MAJOR.MINOR.PATCH for Cocoapods but we cannot follow all the rules, specially the backward compatibility specifications because we can't break our API.

Regarding 1.x.x tags corresponding to the >=2.5 in the documentation, it's a mistake from our part, we thought it would have been weird to start a repo with a 2.5.0 tag. We may add a note on this in the README soon.
