### ISSUE TITLE
Crash: TrackerQueue (QOS: BACKGROUND)

### ISSUE THREAD

**Issue by sebbbbbb** [at-internet/atinternet-apple-sdk#92]
Hello,
On my app, in some rares cases the tracker crash because of a concurrent access.
I use the following snippet to setup the tracker :
```swift
 func setup() {
    let tracker = ATInternet.sharedInstance.defaultTracker
    tracker.setLog(log, completionHandler: nil)
    tracker.setSiteId(siteId, completionHandler: nil)
    tracker.setSecuredLog(logSSL, completionHandler: nil)
  }
```

I see that you can provide a sync param to perform operation synchronously and I will do that but it look like setting it to false doesn't work all the times. Probably because the queue priority is set to Background which may defer it's execution.

I'm using version 2.16.2.

![Capture d’écran 2020-08-10 à 11 30 28](https://user-images.githubusercontent.com/25281950/89769467-76a00100-dafd-11ea-836e-cc5f9ee2c4f6.png)
![Capture d’écran 2020-08-10 à 11 30 15](https://user-images.githubusercontent.com/25281950/89769469-77d12e00-dafd-11ea-8283-a30d5427b892.png)

**Comment by nsagnett** [comment]
Hi ! 

It's strongly recommended to use sync version to keep code visibility because in the async version, the `completionHandler` have to be set, it's the function called when async code have been done so if you set nil and you call multiple async functions, this problem occcurs because same ressource can be modified at the same time

Regards,
